### ISSUE TITLE
Runtime error: Freetype library not found

### ISSUE THREAD

**Issue by ThatOneCalculator** [thevarunsharma/Animoji-Animate#3]
How do I fix this? Python 3.7.2, Windows 10.
Here's the traceback:
```
Traceback (most recent call last):
  File "C:\Users\algeb\Downloads\Animoji-Animate-master\animate.py", line 3, in <module>
    from glumpy import app, gloo, gl
  File "C:\Users\algeb\AppData\Local\Programs\Python\Python37-32\lib\site-packages\glumpy\__init__.py", line 7, in <module>
    from . import app
  File "C:\Users\algeb\AppData\Local\Programs\Python\Python37-32\lib\site-packages\glumpy\app\__init__.py", line 16, in <module>
    from glumpy.ext.inputhook import inputhook_manager, stdin_ready
  File "C:\Users\algeb\AppData\Local\Programs\Python\Python37-32\lib\site-packages\glumpy\ext\__init__.py", line 6, in <module>
    from . import freetype
  File "C:\Users\algeb\AppData\Local\Programs\Python\Python37-32\lib\site-packages\glumpy\ext\freetype\__init__.py", line 49, in <module>
    raise RuntimeError('Freetype library not found')
RuntimeError: Freetype library not found
```

**Comment by thevarunsharma** [comment]
You can consider referring to these threads : 
[https://github.com/glumpy/glumpy/issues/85](url)
and [https://stackoverflow.com/questions/53013496/freetype-library-not-found-with-glumpy-python-3-6-win-10](url)

**Comment by ThatOneCalculator** [comment]
I actually tried both of those

**Comment by tomguo1987** [comment]
If you have installed freestyle, go to <your_python_path>\Lib\site-packages\freetype, to find a libfreetype.dll. Copy it to a directory whose path is in your system paths, rename it "freetype.dll", then you should be free from this assert. It worked for me on windows 10.

**Comment by ThatOneCalculator** [comment]
Thank you for replaying so late into the issue! I actually don't even use windows anymore 😅
